### ISSUE TITLE
Field and Column filters on API Endpoints

### ISSUE THREAD

**Issue by jawa-the-hutt** [sowderca/connectwise-rest-api#10]
I wanted to double check and make sure I'm not missing something in your API documentation, but I have yet to see how to include the `fields` and `columns` query string parameters that are allowed for within the CW API for GET requests. 

I use these pretty extensively to limit the amount of data returned to a client on a mobile device/hotspot as well as within Azure to limit the overall amount of bandwidth use needed (and charged for!) to iterate through a large amount of records.  For instance, I have an Azure function that will go grab all of our active customers (2500 out of 13000 total) and bringing back the full company record for 2500 customers uses a lot of bits and bytes.

Is this possible, or would this be an enhancement request?

**Comment by sowderca** [comment]
It is possible now, however the typings and documentation could definitely be improved. 

You can filter the response by using  ```extraQueryParams?: any``` like ```{ fields: 'id, name' }```  so a request would look something like

```typescript
'use strict';

import { Connectwise as CW } from 'connectwise-rest-api';

export const ConnectWise = new CW('url', 'company', 'publicKey', 'privateKey');

ConnectWise.CompaniesApi.companyCompaniesGet( { conditions: '(status/id=1 or status/id=20)', pageSize: 1000 }, { fields: 'id,name,status' }).then( response => {
	console.log(response);
});

```

**Comment by jawa-the-hutt** [comment]
that worked. thanks for the help
