### ISSUE TITLE
Publish types to @types/connectwise-rest-api

### ISSUE THREAD

**Issue by HugoReeves** [sowderca/connectwise-rest-api#12]
Could you please publish the types for this module to the new types system, https://www.npmjs.com/package/@types/connectwise-rest-api

You can check out the new change here, https://github.com/DefinitelyTyped/DefinitelyTyped since ts 2.0 the typings cli is deprecated and you are supposed to use npm @types instead.

**Comment by sowderca** [comment]
@HugoReeves sure thing!

**Comment by sowderca** [comment]
@HugoReeves I've closed this as best practices have chanced since the issue was created and bundling types with the module is commonplace.
