### ISSUE TITLE
Delete Methods return no data

### ISSUE THREAD

**Issue by jawa-the-hutt** [sowderca/connectwise-rest-api#6]
It appears that in all of the Delete by ID methods that nothing is being returned in the response.  This is an issue i'm running into in integrating this library with Azure Functions. 

Going through the CW API documentation, it appears that when you delete an object through the CW API, the API endpoint returns a HTTP Status of '204 - No Content' and it doesn't actually return anything in the response body.

In your code it appears that because you are copying/pasting the same basic response pattern for all of your other methods, you are trying to return a body that isn't there:

```
return fetch(localVarPathWithQueryParameters, fetchParams).then((response) => {
	if (response.status >= 200 && response.status < 300) {
		return response.json();
	} else {
		let error = new Error(response.statusText);
		(error as any).response = response;
		throw error;
	}
});
```

it is specifically the `return response.json();` that I think is the issue.  Since CW doesn't return anything in the body, my guess is that you're not returning anything at all since there isn't anything in `response.json` to return.  this in turn appears to be tripping up Azure Functions as it's expecting some kind of response back and it isn't getting anything passed to it.

Not sure what the best way to address this is going to be.  Technically, you should probably be passing the '204 - No Content' back all the way through and let whatever code is calling your method deal with it there. 

However, i guess you could just return a '200 - OK' for these and the calling code would probably be happy.

**Comment by jawa-the-hutt** [comment]
As a separate comment aside, I would say that because of the repeatable pattern you've setup for your methods and classes, that I've been able to condense everything in the Azure Function into one actual function. I then just pass the Method name, the Class name and any other needed parameters for a specific endpoint into the function.

essentially, in about 30 lines of code, the entire CW API infrastructure is now available for use in Azure Functions which in turn makes it available across a whole host of other things like O365, SharePoint Online, Azure SQL, Logic Apps, etc.

Good Job!

**Comment by sgtoj** [comment]
Being that `204` status is already `NO CONTENT`, in my opinion, it should just return `204`. I would vote against returning `200`. Instead, return `204` to let the consumer/user decided how to handle it.

**Comment by sgtoj** [comment]
After reviewing the source, I believe the behavior should remain unchanged. Keeping it unchanged would keep it consistent with other API response. The customer/user should assume no returned data and thrown error, is a successful request. 

A possible solution, although it is a breaking change, would be returned object that includes meta data. This is a common practice too.

```js
// recommended example
return fetch(localVarPathWithQueryParameters, fetchParams).then((response) => {
    if (response.status >= 200 && ! < 300) {
        return Promise.resolve({
            status: response.status,
            data: response.json()
        });
    } else {
        let error = new Error(response.statusText);
        (error as any).response = response;

        return Promise.resolve({  // recommend resolve(), but reject() would be acceptable too
            status: response.status,
            error: error
        });
    }
});

// alternative example
return fetch(localVarPathWithQueryParameters, fetchParams).then((response) => {
    if (response.status >= 200 && response.status < 300) {
        return Promise.resolve({
            status: response.status,
            data: response.json()
        })
    } else {
        let error = new Error(response.statusText);
        (error as any).response = response;
        throw error;
    }
});


```

**Comment by jawa-the-hutt** [comment]
Ok, fair enough.  I had basically did the error check on my side in the mean time so if things remain unchanged, then I'm all set to go.

thanks for checking on this.
